#!/usr/bin/env python3
"""Validate the translation table and generate the browser/CommonJS catalog."""

import argparse
from collections import Counter
import csv
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs' / 'ui_copy_review.tsv'
OUTPUT = ROOT / 'static' / 'js' / 'standterm-messages.js'
FIELDS = ['key', 'current_en', 'en', 'zh-TW', 'context', 'placeholders', 'constraints', 'status', 'source']
STATUSES = {'proposed', 'retain', 'remove', 'source-approved', 'translation-reviewed'}
PLACEHOLDER = re.compile(r'\{[A-Za-z_][A-Za-z0-9_]*\}')


def build_catalog(source):
    messages = {'en': {}, 'zh-TW': {}}
    seen = set()
    with source.open(encoding='utf-8-sig', newline='') as handle:
        reader = csv.DictReader(handle, delimiter='\t')
        if reader.fieldnames != FIELDS:
            raise ValueError('Unexpected translation table columns')
        for row in reader:
            key = row['key']
            if None in row or any(value is None for value in row.values()):
                raise ValueError(f'Invalid columns for {key}')
            if not re.fullmatch(r'[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+', key) or key in seen:
                raise ValueError(f'Invalid or duplicate key: {key}')
            seen.add(key)
            if any(any(char in value for char in '\t\r\n') for value in row.values()):
                raise ValueError(f'Use escaped line breaks in {key}')
            if row['status'] not in STATUSES:
                raise ValueError(f'Unknown status for {key}')
            if row['status'] == 'remove':
                if row['en'] or row['zh-TW']:
                    raise ValueError(f'Removal row must have empty text: {key}')
                continue
            if not row['en'].strip():
                raise ValueError(f'Missing English source: {key}')
            expected = Counter(PLACEHOLDER.findall(row['placeholders']))
            for language in ('en', 'zh-TW'):
                text = row[language]
                if text and Counter(PLACEHOLDER.findall(text)) != expected:
                    raise ValueError(f'Placeholder mismatch in {key}: {language}')
            if row['status'] not in {'source-approved', 'translation-reviewed'}:
                continue
            messages['en'][key] = row['en'].replace('\\n', '\n')
            if row['status'] == 'translation-reviewed' and row['zh-TW'].strip():
                messages['zh-TW'][key] = row['zh-TW'].replace('\\n', '\n')
    return messages


def render_catalog(messages, desktop=False):
    payload = json.dumps(messages, ensure_ascii=True, indent=4, sort_keys=True)
    source = 'desktop_ui_copy_review.tsv' if desktop else 'ui_copy_review.tsv'
    global_name = 'StandTermDesktopMessages' if desktop else 'StandTermMessages'
    return (
        f'// Generated by scripts/build_ui_messages.py. Edit docs/{source}.\n'
        '(function (root) {\n'
        "    'use strict';\n"
        f'    const messages = {payload};\n'
        "    if (typeof module === 'object' && module.exports) module.exports = messages;\n"
        f'    else root.{global_name} = messages;\n'
        '})(globalThis);\n'
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed catalog is stale')
    parser.add_argument('--desktop', action='store_true', help='Build the independent Desktop catalog')
    args = parser.parse_args(argv)
    source = ROOT / 'docs' / 'desktop_ui_copy_review.tsv' if args.desktop else SOURCE
    output = ROOT / 'desktop' / 'messages.js' if args.desktop else OUTPUT
    try:
        expected = render_catalog(build_catalog(source), desktop=args.desktop)
        if args.check:
            if not output.is_file() or output.read_text(encoding='utf-8') != expected:
                command = 'scripts/build_ui_messages.py' + (' --desktop' if args.desktop else '')
                raise ValueError(f'UI catalog is stale; run {command}')
        else:
            output.write_text(expected, encoding='utf-8')
    except (OSError, ValueError) as exc:
        parser.exit(1, f'{exc}\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
